proxy:
  image: jwilder/nginx-proxy
  ports:
     - "80:80"
  volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
     DEFAULT_HOST: www.mysite.com

frontend:
  build: frontend/
  environment:
     VIRTUAL_HOST: www.mysite.com
