proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  links:
    - frontend
    - php
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
    DEFAULT_HOST: www.candycrm.com

frontend:
  build: frontend/
  environment:
    VIRTUAL_HOST: www.candycrm.com

php:
  image: php:5.6-apache
  volumes:
    - backend/public/:/var/www/html/
  environment:
    VIRTUAL_HOST: api.candycrm.com